### ISSUE TITLE
Wrapper breaks in latest version of Wix (parent is null or undefined)

### ISSUE THREAD

**Issue by esdin-oculus** [skorokhod-andrii/wix-event-wrapper#1]
It seems like a recent Wix update breaks the functionality of this wrapper on live (though it still functions as expected in editor view)

Breaks at line 25

const getMethods = (child, parent) => (
			Object.getOwnPropertyNames(parent)     <--

with parent as null.

**Comment by skorokhod-andrii** [comment]
Thank you. Fixed in last commit.
